### ISSUE TITLE
Also Changed Launcher Icon

### ISSUE THREAD

**Issue by borth92** [faviouz/fix-spotify-icon#1]
I am running Elementary OS Freya beta. Your fix did exactly what I needed on the tray, but now my launcher opens as the same icon (small and monochrome). On my other laptop it did not do this, I kept the original launcher icon and the fix just replaced the tray icon. Any suggestions?

**Comment by pkill37** [comment]
I'm not sure what you mean. Can you screenshot it please? :)

**Comment by borth92** [comment]
Screenshot is attached. Thank you for the quick reply. At first I tried 
a forked version of your fix that specified Elementary OS and it worked, 
but after reboot the issue returned. Any help is much appreciated. Like 
I said, I did the same thing on another laptop with the same setup 
(possibly exactly the same), and it does not have the issue. Once again, 
thank you for replying so fast :)

-Dan

**Comment by pkill37** [comment]
I think you forgot to attach the screenshot. :stuck_out_tongue_winking_eye:

**Comment by borth92** [comment]
I can see it in my sent folder with the attachment, but I'll attach it 
to this email just in case. Let me know if, for some reason, you're not 
seeing attachments on this email either. Then I'll make a public folder 
on dropbox and send you a link :)

**Comment by pkill37** [comment]
When you reply to GitHub issues via email, you're not emailing **me** directly. You're emailing notifications@github.com, which then automagically posts your message here. I guess it doesn't copy attachments.

**Comment by borth92** [comment]
Its cool, I'm at work now, as soon as I'm home I'll just send you a Dropbox link to it :)

--- Original Message ---

**Comment by borth92** [comment]
https://www.dropbox.com/s/gbv9epmklxsisvh/Screenshot%20from%202014-11-27%2020%3A42%3A15.png?dl=0

Hopefully the link to the screenshot works. Essentially when I click Spotify on the dock, it creates a new icon on the dock for the open program with the monochrome icon. Not sure if the launcher pulls an upscaled version of the same icon as the top bar, but it looks extremely ugly.

--- Original Message ---
