### ISSUE TITLE
Doesn't work with the latest verson

### ISSUE THREAD

**Issue by ammarx** [faviouz/fix-spotify-icon#3]
After installing the latest version of spotify and re-running the command, I still have the default icon:
![screenshot from 2015-03-26 18 26 04](https://cloud.githubusercontent.com/assets/4668212/6847089/a0f9a8fe-d3e5-11e4-98c1-9c46e7310746.png)

**Comment by pkill37** [comment]
Can you give me some detailed information about your distribution? Any customizations you've made?

**Comment by ammarx** [comment]
I am running: Ubuntu 14.04,
After todays spotify update, I noticed that the icon has changed back. Though this time its not pixelated. However I didn't like that green icon, so I decided to rerun the fix-spotify-icon. Rerunning it after the update didn't do anything..

The only customizations I have made are using Unity Tweak Tool. In which I have the Panel Transparency Level to max. However reverting those changes doesn't do anything.

The transparency is just to have the top bar as transparent as possible. Here is an image with the transparency on:

![transp](https://cloud.githubusercontent.com/assets/4668212/6848581/e0d5e582-d3ef-11e4-8aff-f2ff3914036f.png)

Here it is with it off:
![transpoff](https://cloud.githubusercontent.com/assets/4668212/6848592/f1455d44-d3ef-11e4-9b53-7b271ba575ba.png)

Its not such a big issue that the icon has changed... However when I access HUD or (start menu/window key _not sure what this is called in ubuntu_) it changes the icon to:

![screenshot from 2015-03-26 19 42 04](https://cloud.githubusercontent.com/assets/4668212/6848636/37efbfc8-d3f0-11e4-84aa-1ffd74a7cd05.png)

Regards,
Ammar Ahmad

**Comment by pkill37** [comment]
Spotify has likely been changed in the way the icon is loaded.

I will look into it later. Feel free to continue pinging me to fix it. :)

**Comment by ammarx** [comment]
Thanks :)

**Comment by ammarx** [comment]
I managed to fix the issue by replacing all the icons in the resources.zip file and Icons folder.

![screenshot from 2015-03-27 01 10 12](https://cloud.githubusercontent.com/assets/4668212/6855914/15bec5b0-d41e-11e4-8633-548c65b64b0b.png)

In HUD:

![screenshot from 2015-03-26 20 29 34](https://cloud.githubusercontent.com/assets/4668212/6849757/ddf1c33e-d3f6-11e4-81ba-065dd1cafc8c.png)

However I was wondering if you can provide me with 512x512 of that icon.

**Comment by raivis-vitols** [comment]
Saw the Spotify in updates list and immediately thought about the icon. And here you go, the ugly icon is back. Looking forward for the update. :)

**Comment by jo-m1b** [comment]
Hi,

For Ubuntu, i made monochrome color conversion for these icons. 
I'm not designer so it's not optimal but do the job.
You can download them here : 

https://dl.dropboxusercontent.com/u/161399/fix-spotify-icon/spotify-linux-512.png
https://dl.dropboxusercontent.com/u/161399/fix-spotify-icon/spotify-linux-256.png
https://dl.dropboxusercontent.com/u/161399/fix-spotify-icon/spotify-linux-128.png
https://dl.dropboxusercontent.com/u/161399/fix-spotify-icon/spotify-linux-64.png
https://dl.dropboxusercontent.com/u/161399/fix-spotify-icon/spotify-linux-48.png
https://dl.dropboxusercontent.com/u/161399/fix-spotify-icon/spotify-linux-32.png
https://dl.dropboxusercontent.com/u/161399/fix-spotify-icon/spotify-linux-24.png
https://dl.dropboxusercontent.com/u/161399/fix-spotify-icon/spotify-linux-22.png
https://dl.dropboxusercontent.com/u/161399/fix-spotify-icon/spotify-linux-16.png

You have to put them into /opt/spotify/spotify-client/Data/resources.zip (in the folder _linux)

**Comment by keevitaja** [comment]
+1 for the update!

**Comment by HeroCC** [comment]
Same issue here, update soon!

**Comment by tristan-k** [comment]
Here's a dark version. For themes like Snowbird (http://gnome-look.org/content/show.php/?content=167346) or Zukimac.

![spotify-linux-256](https://cloud.githubusercontent.com/assets/732025/7117060/9b5ba626-e1f6-11e4-9b3c-3a4f6859e633.png)

http://www48.zippyshare.com/v/CsijhjVu/file.html

**Comment by rcatajar** [comment]
Hey @ammarx ,

Are you working on the fix ? Otherwise I can take care of it probably during the week and submit a PR

**Comment by ammarx** [comment]
Done.
https://github.com/faviouz/fix-spotify-icon/pull/4

**Comment by rcatajar** [comment]
:+1: Thanks

**Comment by jo-m1b** [comment]
;)

**Comment by togruta** [comment]
Fix not working for me. On Ubuntu 15.04.

**Comment by pkill37** [comment]
I have merged #4. It now works with newer versions of Spotify. It also updates the icon in the HUD. Thanks goes to @ammarx. :)

@togruta: Ubuntu 15.04 is still beta. I will deal with it later. However you're welcome to offer more feedback or submit a PR for that.

**Comment by togruta** [comment]
Alright, no problem. 15.04 comes off Beta in three days, so I'll just hold my horses for a couple of weeks afterwards. Not a critical enough bug to bug too much about it :)
